# Site settings
title: Kyle Steenkamp
description: whoami

# User settings
username: Kyle Steenkamp
user_description: DevOps ~ Platform Engineering
user_title: Leader // Hacker // Optimizer // Guitarist 
email: kyle@therightway.co.za
github_username:  kylenesium.github.io

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
