# Site settings
title: Kyle Steenkamp
description: whoami
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kyle Steenkamp
user_description: All round nice guy.
user_title: DevOps Engineer
email: kyle.steenkamp@outlook.com
twitter_username: lorem_ipsum
github_username:  kylenesium.github.io
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
